thoth-station/management-api

openapi/openapi.yaml, thoth/management_api/api_v1.py
This is usefull if there are server side errors. An example I observed - if
there is ongoing transaction on Dgraph side, Dgraph refuses to update schema
and an error is returned back to user.
=> Report back an error message if schema initialization fails

openapi/openapi.yaml, thoth/management_api/api_v1.py
- Added endpoint GET `/package-analyzer/{analysis_id}` to management API to retrieve package-analyzer results
- Added endpoint GET `/package-analyzer/{analysis_id}/log` to management API to retrieve logs of a package-analyzer run
- Added endpoint GET `/package-analyzer/{analysis_id}/status` to management API to retrieve logs of a package-analyzer run
- Added a secret to `post_analyze_package`
=> Add Package Analyzer log & status endpoints

Pipfile, Pipfile.lock, openapi/openapi.yaml
Fixes: https://github.com/thoth-station/management-api/issues/255
- Removed pinned down version for `openapi-spec-validator`
=> Add schema for Info

openshift/deployment-template.yaml, thoth/management_api/openapi_server.py
This way we will not need to manually trigger the initialization endpoint to
update the schema to the latest version in test deployment. It's especially
usefull for thoth-storages update - test environment can bump schema version
automatically.
=> Initialize schema on fresh deployment based on env variable

openapi/openapi.yaml
This way there is no need to update/redeploy management-api on every change on
Amun and parameters can be propagated.
=> Allow additional properties in context

.thoth.yaml
Sesheta and pacospace cannot release.
https://github.com/thoth-station/management-api/issues/500
https://github.com/thoth-station/management-api/issues/496
=> Add maintainers

openapi/openapi.yaml
```
connexion.exceptions.InvalidSpecification: False is not of type 'string'
Failed validating 'type' in schema:
{'default': False, 'type': 'string'}
```
=> Openapi schema fix

openapi/openapi.yaml, thoth/management_api/api_v1.py
It might not be a good idea to keep it exposed. It served its purpose during development but can be removed now.
=> Remove erase endpoint

openapi/openapi.yaml, thoth/management_api/api_v1.py
This endpoint is obsolete, the information it provided is available via metrics.
=> Remove /graph/version endpoint

openapi/openapi.yaml
Fixes: https://github.com/thoth-station/adviser/issues/1712
=> Remove version clash boot from the example

openapi/openapi.yaml
Fixes: https://github.com/thoth-station/management-api/issues/774
=> Fix wrong rule version range specified in OpenAPI spec

openapi/openapi.yaml
Fixes: https://github.com/thoth-station/management-api/issues/813
=> Make warehouse_api_url optional

thoth/management_api/api_v1.py
Related: https://github.com/thoth-station/solver/issues/5111
Related: https://github.com/thoth-station/graph-refresh-job/issues/669
Related: https://github.com/thoth-station/thoth-application/issues/2272
Allow passing new environment variable for solvers, which would check indexes for possible dependencies (cross-index resolution).
=> Allow passing dependency indexes to the solver workflow

openapi/openapi.yaml
- No
- Update the schema for the `/dependency-monkey/python/` endpoint to match the requirements of the amun-api `/inspect` endpoint schema
- Update base image used to thoth-s2i recent image and python version to 3.8
- Remove `CutPreReleasesSieve` pipeline unit
=> Update dependency-monkey endpoint schema

Pipfile, Pipfile.lock
See https://github.com/thoth-station/prescriptions/pull/19748
Fixes https://github.com/thoth-station/management-api/issues/874
- No
=> Downgrade markupsafe <2.1.0

openapi/openapi.yaml
They are not used during the dependency monkey run.
=> Remove requirements_locked and constraints from dependency monkey

openapi/openapi.yaml
- No
- Use `python3.8` as a default value for the dependency-monkey endpoint.
- Fix url to amun-api
=> Use py38 as default in api schema

openapi/openapi.yaml, thoth/management_api/api_v1.py
Partially addresses: https://github.com/thoth-station/thoth-application/issues/2513 (task 3 / 4)
Related-to: https://github.com/thoth-station/management-api/issues/887
New post endpoints for `/graph/sync-job/{component-name}`, that will trigger the sync job for those documents.
Component names:
1. adviser
2. solver
3. revsolver
4. package-extract
5. provenance-checker
6. security-indicators
/cc @harshad16 @fridex
=> Enable sync job to be called from the management api

thoth/management_api/api_v1.py
Fix for https://github.com/thoth-station/management-api/issues/863
Code will check if key 'warehouse_api_url' exists in the dict, if not sets None as default
=> Fix: To check if 'warehouse_api_url' key exists

openapi/openapi.yaml
…
Fix the description of index_url in /python/package-index/state
I'm pretty sure that index_url is not a secret, given the rest of the endpoint
and the register one.
=> Fix the description of index_url in /python/package-index/state

.flake8, .pre-commit-config.yaml
This allow to use flake8 with local dev tools (python-language-server in
particular)
=> Get flake8 config out of pre-commit config

.aicoe-ci.yaml
All currents PRs seems blocked by aicoe-ci/build-check 
Fix what looks like a typo in .aicoe-ci.yaml, in the case it's related to the
build-check failing.
=> Tentative fix for aicoe-ci/build-check

thoth/management_api/api_v1.py
Correct the error type for exception handle in get_log
Related-to: https://github.com/thoth-station/management-api/issues/920
The exception would be handled properly and give 404 not found, instead of 500 internal error.
=> :recycle: Correct the error type for exception handle in get_log
