thoth-station/management-api

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .zuul.yaml
=> added github and zuul configs

Pipfile, Pipfile.lock
See https://github.com/zalando/connexion#the-swagger-ui-console for more info. Otherwise Swagger UI is not present.
=> New connexion requires swagger-ui extras

openshift/deployment-template.yaml
Depends-On: https://github.com/thoth-station/core/pull/180
=> Token secret

thoth/management_api/swagger.yaml
Depends-On: https://github.com/thoth-station/amun-client/pull/28
=> Provide hardware requirements in swagger

Pipfile, Pipfile.lock, thoth/management_api/api_v1.py, thoth/management_api/entrypoint.py
=> added prometheus metric export for all things REST

openshift/deployment-template.yaml
=> raised the limits

thoth/management_api/api_v1.py
=> Fix wrong method name in call

thoth/management_api/api_v1.py, thoth/management_api/swagger.yaml
Relevant: https://github.com/thoth-station/common/pull/333
=> Expose parameter for limiting number of latest versions

openshift/buildConfig-template.yaml, openshift/deployment-template.yaml, openshift/imageStream-template.yaml
=> reworked the service account part

openshift/deployment-template.yaml
=> Increase memory requirements

Pipfile, Pipfile.lock
Related: https://github.com/thoth-station/management-api/issues/73
=> Fix to make updates of dependencies possible

thoth/management_api/api_v1.py, thoth/management_api/swagger.yaml
Fixes: https://github.com/thoth-station/management-api/issues/100
=> Remove sync endpoint

openapi/openapi.yaml, thoth/management_api/api_v1.py
Depends-On: https://github.com/thoth-station/common/pull/420
=> Provide graph-refresh endpoint

openapi/openapi.yaml, thoth/management_api/api_v1.py
Depends-On: https://github.com/thoth-station/graph-sync-job/pull/212
Depends-On: https://github.com/thoth-station/common/pull/427
=> Provide graph-sync multiple endpoint

openapi/openapi.yaml, thoth/management_api/api_v1.py, thoth/management_api/configuration.py
Depends-On: https://github.com/thoth-station/common/pull/443
Endpoint to handle package analyzer jobs
=> endpoint to run package analyzer jobs

openapi/openapi.yaml, thoth/management_api/api_v1.py
=> Corrected descriptions

openapi/openapi.yaml
- Fixes analysisResponseError and analysisStatus
- Puts all the endpoints under `Package Analyzer` tag
=> Fix analysis response error

openapi/openapi.yaml, thoth/management_api/api_v1.py
Added `package analyzer` documents to be synced in `graph sync`
=> Add package analyzer documents to graph sync

openapi/openapi.yaml, thoth/management_api/api_v1.py
Related: https://github.com/thoth-station/storages/pull/974
=> Provide an endpoint for enabling and disabling a Python package index

thoth/management_api/api_v1.py
=> Fix wring import when importing performance models

openapi/openapi.yaml, thoth/management_api/api_v1.py
Related: https://github.com/thoth-station/common/pull/473 https://github.com/thoth-station/graph-refresh-job/pull/256
=> Provide an option to schedule solvers with transitive flag

openapi/openapi.yaml
Related: https://github.com/thoth-station/solver/issues/289
=> Notify user about disjoint flags

openapi/openapi.yaml, thoth/management_api/api_v1.py
Related-To: https://github.com/thoth-station/user-api/pull/577
=> [WIP] Add Info

openshift/deployment-template.yaml, thoth/management_api/openapi_server.py
Related: https://github.com/thoth-station/user-api/issues/609
=> Redirect to HTTPS instead of HTTP

thoth/management_api/api_v1.py
Fixes: https://github.com/thoth-station/management-api/issues/271
=> Fix Wrong API Call

thoth/management_api/openapi_server.py
Related: https://github.com/thoth-station/user-api/pull/640
=> Fix redirect to swagger UI

thoth/management_api/api_v1.py, thoth/management_api/openapi_server.py
... otherwise connexion fails to register methods from openapi
=> Move graph instantiation to openapi module

Pipfile, Pipfile.lock
See: https://docs.sentry.io/platforms/python/aiohttp/
Related: https://github.com/thoth-station/common/pull/539
=> Add aiocontextvars for sentry-sdk integration with aiohttp

openapi/openapi.yaml, thoth/management_api/api_v1.py
Related: https://github.com/thoth-station/common/pull/608
=> Add runtime environment parameter to dependency monkey endpoint

openapi/openapi.yaml, thoth/management_api/api_v1.py
Depends-On: https://github.com/thoth-station/common/pull/612
=> Add a way to expose pipeline configuration

openapi/openapi.yaml
=> Add default value to software stacks generated

openapi/openapi.yaml
Related: https://github.com/thoth-station/adviser/pull/834
=>  Add an example for filter sieve for dependency monkey runs

openshift/buildConfig-template.yaml
=> Increase memory for OOM during build

openshift/buildConfig-template.yaml
This environment variable is used on runtime.
=> Remove unused environment variable

thoth/management_api/openapi_server.py
Closes https://github.com/thoth-station/user-api/issues/893
=> Replicate same behavior as user-api

thoth/management_api/api_v1.py
=> Fix pre-commit issues

.thoth.yaml
This caused issues on resolver side.
=> Remove latest versions restrictions

thoth/management_api/api_v1.py
Fixes: https://github.com/thoth-station/management-api/issues/511
=> Fix parse python solve name

openapi/openapi.yaml, thoth/management_api/api_v1.py
Use the new workflow status method on status endpoints. 
Closes #507
=> Added new workflow status method

thoth/management_api/api_v1.py
Fixes: #529 
Related: https://github.com/thoth-station/user-api/pull/1019 https://github.com/thoth-station/common/pull/949
=> Fix obtaining logs for DM and solvers when Argo workflows are used

thoth/management_api/openapi_server.py
=> Provide service version

thoth/management_api/api_v1.py, thoth/management_api/openapi_server.py
=> Pre commit fixes

openapi/openapi.yaml, thoth/management_api/api_v1.py
Related: https://github.com/thoth-station/common/pull/955
=> Introduce a way to parametrize predictor

openapi/openapi.yaml, thoth/management_api/api_v1.py
Related: https://github.com/thoth-station/common/pull/959 https://github.com/thoth-station/thoth-application/pull/347
=> Introduce a way to parametrize predictor on API endpoint

openapi/openapi.yaml
Fixes: https://github.com/thoth-station/adviser/issues/1088
=> Remove additional property configuration

openapi/openapi.yaml, thoth/management_api/api_v1.py
Fixes: https://github.com/thoth-station/management-api/issues/599
Add optional index URL for solver analysis
=> Add optional index URL for solver analysis

thoth/management_api/api_v1.py
=> Do not schedule solvers if index is not enabled

openapi/openapi.yaml
=> Remove unused parameters

Pipfile.lock
relocked pipfile
Related-To: #631
=> relocked pipfile

.aicoe-ci.yaml
Related-To: https://github.com/thoth-station/thoth-application/issues/545
=> update aicoe yaml

Pipfile.lock
Relock Pipfile.lock with package updates
fixing typing_extension issue.
=> Relock Pipfile.lock with package updates

thoth/management_api/api_v1.py
fix the pre-commit issues
Fixes: https://github.com/thoth-station/management-api/pull/653#issuecomment-759603142
=> fix the pre-commit issues

openapi/openapi.yaml, thoth/management_api/api_v1.py
Fixes: https://github.com/thoth-station/storages/issues/2080
Introduce async graph schema update.
=> Introduce async graph update

.github/ISSUE_TEMPLATE/kebechet_info.md, .github/ISSUE_TEMPLATE/kebechet_update.md
=> Add Kebechet update and info templates

.github/ISSUE_TEMPLATE/kebechet_update.md
=> Add missing template title

thoth/management_api/openapi_server.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/529
Introduce metric to expose revision migration available from thoth-storages library
=> Expose schema revision

thoth/management_api/openapi_server.py
Related-To: https://github.com/thoth-station/management-api/pull/672#issuecomment-763193660
=> Standardize metric name 

thoth/management_api/openapi_server.py
=> Run it once and set default to 1 when revision is up

openapi/openapi.yaml, thoth/management_api/api_v1.py
Fixes: https://github.com/thoth-station/management-api/issues/688
Related: https://github.com/thoth-station/storages/pull/2204
=> Implement endpoints that manipulate with hardware environments

thoth/management_api/openapi_server.py
Related: https://github.com/thoth-station/user-api/issues/1253
=> Provide an option to validate responses

thoth/management_api/api_v1.py
Related: https://github.com/thoth-station/storages/pull/2221
Related: https://github.com/thoth-station/adviser/pull/1670
=> Persist request to Dependency Monkey runs

thoth/management_api/api_v1.py
Depends-On: https://github.com/thoth-station/common/pull/1115/
Related: https://github.com/thoth-station/thoth-application/issues/946
=> Always sync results of package-extract on management-api

README.rst
=> Minor README correction

thoth/management_api/api_v1.py
Related: https://github.com/thoth-station/thoth-application/issues/902
Related: https://github.com/thoth-station/thoth-application/pull/912
Depends-On: https://github.com/thoth-station/common/pull/1109
=> Adjust parameters supplied to Dependency Monkey scheduling

.aicoe-ci.yaml, .pre-commit-config.yaml, .prow.yaml
n/a
This is just a bunch of standard updates to CI config
=> :arrow_up: update pre-commit plugins, CI related configs

openapi/openapi.yaml
=> Fix typo in description

openapi/openapi.yaml, thoth/management_api/api_v1.py
Closes: https://github.com/thoth-station/thoth-application/issues/808
Depends-On: https://github.com/thoth-station/common/pull/1152
=> Introduce endpoints for purging data

openapi/openapi.yaml, thoth/management_api/api_v1.py
Related: https://github.com/thoth-station/thoth-application/issues/1403
Depends-On: https://github.com/thoth-station/storages/pull/2313
=> Create endpoints for managing Python solver rules

Pipfile, Pipfile.lock, openapi/openapi.yaml
Fixes: #762
Fixes: https://github.com/thoth-station/management-api/issues/764
=> Fix module not found error for flask._compat

openapi/openapi.yaml
Fixes: https://github.com/thoth-station/management-api/issues/769
=> Delete solver rules endpoint returns a single rule deleted

openapi/openapi.yaml, thoth/management_api/api_v1.py
Related: https://github.com/thoth-station/common/pull/1162
Related: https://github.com/thoth-station/storages/issues/2308
=> Provide force_sync option when scheduling solvers

openapi/openapi.yaml, thoth/management_api/api_v1.py, thoth/management_api/exceptions.py
Related: https://github.com/thoth-station/thoth-application/issues/1822
=> Enable configuring monitoring of Python package indexes

Pipfile.lock
Dependency update for the management-api
This update has bump of storage and commons.
=> Dependency update for the management-api

thoth/management_api/api_v1.py
Fixes: https://github.com/thoth-station/management-api/issues/809
=> Fix import statement

.prow.yaml
=> Update pre-commit base image version

thoth/management_api/api_v1.py
Fixes https://github.com/thoth-station/management-api/issues/889
- No
=> Fix retrieving unsolvable packages
